import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0F1115',
  },
  header: {
    paddingTop: 15,
    paddingHorizontal: 24,
    marginBottom: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  title: {
    fontSize: 28,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: -0.5,
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1C1F26',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  indicator: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginRight: 6,
  },
  statusText: {
    color: '#8A8F98',
    fontSize: 10,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  feedContainer: {
    flex: 1,
    paddingHorizontal: 20,
  },
  clipCard: {
    backgroundColor: '#1C1F26',
    borderRadius: 16,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#2A2F3A',
    flexDirection: 'row',
    alignItems: 'center',
  },
  clipIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: '#0F1115',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  clipContentContainer: {
    flex: 1,
    justifyContent: 'center',
  },
  clipActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 8,
  },
  clipType: {
    color: '#3B82F6',
    fontSize: 12,
    fontWeight: '700',
  },
  clipTime: {
    color: '#8A8F98',
    fontSize: 12,
  },
  clipTitle: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '600',
    marginBottom: 4,
  },
  actionBtnIcon: {
    width: 40,
    height: 40,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
  },
  emptyText: {
    color: '#4C5361',
    textAlign: 'center',
    marginTop: 50,
  },
  inputArea: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: '#1C1F26',
    borderTopWidth: 1,
    borderTopColor: '#2A2F3A',
    alignItems: 'flex-end',
  },
  textInput: {
    flex: 1,
    backgroundColor: '#0F1115',
    color: '#FFFFFF',
    borderRadius: 20,
    paddingHorizontal: 20,
    paddingTop: 15,
    paddingBottom: 15,
    fontSize: 15,
    maxHeight: 120,
    borderWidth: 1,
    borderColor: '#2A2F3A',
  },
  sendButton: {
    marginLeft: 12,
    marginBottom: 5,
  },
  attachButton: {
    marginRight: 12,
    marginBottom: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.85)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    backgroundColor: '#1C1F26',
    borderRadius: 20,
    padding: 24,
    width: '100%',
    maxWidth: 400,
    borderWidth: 1,
    borderColor: '#2A2F3A',
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#FFF',
    marginBottom: 8,
  },
  modalSubtitle: {
    fontSize: 14,
    color: '#8A8F98',
    marginBottom: 24,
    lineHeight: 20,
  },
  modalInput: {
    backgroundColor: '#0F1115',
    color: '#FFF',
    padding: 16,
    borderRadius: 12,
    fontSize: 16,
    borderWidth: 1,
    borderColor: '#2A2F3A',
    marginBottom: 20,
  },
  modalButton: {
    backgroundColor: '#4A62EB',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
  },
  modalButtonText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: '700',
  },
  targetOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#0F1115',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2A2F3A',
    marginBottom: 10,
  },
});
